apiVersion: apps/v1
kind: Deployment
metadata:
  name: oam-go
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: oam-go
  template:
    metadata:
      labels:
        app: oam-go
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: oam-go
      containers:
        - name: oam-operator
          image: xtaodocker/oam-operator:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "32Mi"
              cpu: "10m"
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 10001
