apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: oam-go
  name: applications.core.oam.dev
spec:
  group: core.oam.dev
  names:
    kind: ApplicationConfiguration
    plural: applications
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: oam-go
  name: components.core.oam.dev
spec:
  group: core.oam.dev
  names:
    kind: Component
    plural: components
  scope: Namespaced
  version: v1alpha1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: oam-go
  name: oam-go
  namespace: oam
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: oam-go
  name: oam
rules:
- apiGroups:
  - ""
  resources:
  - events
  - configmaps
  - configmaps/finalizers
  - secrets
  - secrets/finalizers
  - services
  - services/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - daemonsets
  - daemonsets/finalizers
  - deployments
  - deployments/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  - horizontalpodautoscalers/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  - ingresses/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - flagger.app
  resources:
  - canaries
  - canaries/status
  - metrictemplates
  - metrictemplates/status
  - alertproviders
  - alertproviders/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  - virtualservices/finalizers
  - destinationrules
  - destinationrules/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - virtualnodes
  - virtualnodes/finalizers
  - virtualservices
  - virtualservices/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - split.smi-spec.io
  resources:
  - trafficsplits
  - trafficsplits/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - specs.smi-spec.io
  resources:
  - httproutegroups
  - httproutegroups/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - gloo.solo.io
  resources:
  - upstreams
  - upstreams/finalizers
  - upstreamgroups
  - upstreamgroups/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - projectcontour.io
  resources:
  - httpproxies
  - httpproxies/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- nonResourceURLs:
  - /version
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: oam-go
  name: oam-go
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oam-go
subjects:
- kind: ServiceAccount
  name: oam-go
  namespace: oam
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oam-go
  namespace: oam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oam-go
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: oam-go
    spec:
      containers:
      - image: xtaodocker/oam-operator:1.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - wget
            - --quiet
            - --tries=1
            - --timeout=2
            - --spider
            - http://localhost:8000/healthz
          timeoutSeconds: 5
        name: flagger
        ports:
        - containerPort: 8000
          name: http
        readinessProbe:
          exec:
            command:
            - wget
            - --quiet
            - --tries=1
            - --timeout=2
            - --spider
            - http://localhost:8000/healthz
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 32Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 10001
      serviceAccountName: oam-go
