apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: applications.core.oam.dev
spec:
  group: core.oam.dev
  version: v1alpha1
  names:
    kind: ApplicationConfiguration
    plural: applications
  scope: Namespaced

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: components.core.oam.dev
spec:
  group: core.oam.dev
  version: v1alpha1
  names:
    kind: Component
    plural: components
  scope: Namespaced